### ISSUE TITLE
The navbar doesn't look good. Going to shift the navbar items to the right and also improve its aesthetics.

### ISSUE THREAD

**Issue by binary-amigo** [Nandini80/CityPlus#1]

**Comment by Nandini80** [comment]
Kindly share the screenshot after you are done with the changes.I am assigning this task to you.

**Comment by SahilThakur02** [comment]
@Nandini80 Can I work on it?

**Comment by Nandini80** [comment]
any update?

**Comment by Gursimranjeet-Singh** [comment]
Have you made any progress?
Since i was thinking of working on user interface.

**Comment by Nandini80** [comment]
@Gursimranjeet-Singh ok then I am assigning this issue to you.Keep me updated.

**Comment by Nandini80** [comment]
@Gursimranjeet-Singh Are you still working on this issue?

**Comment by Gursimranjeet-Singh** [comment]
@Nandhini I was working on design part to improve the ui of the website but
currently due to my college project I am not able to devotee enough time to
this project.
So that's why it is causing delay if you want to assign someone you can
please do it.
I'll will continue working on it even after deadline of phyisict to improve
projects .
Hopefully I will be able to generate a pull request soon

**Comment by Nandini80** [comment]
Ok.

**Comment by SahilThakur02** [comment]
@Nandini80 Assign this to me please. I am a beginner and wish to work on the Navbar.

**Comment by SahilThakur02** [comment]
Created a PR!
[https://github.com/Nandini80/CityPlus/pull/23](url)
 
@Nandini80

**Comment by SahilThakur02** [comment]
@Nandini80 I think this issue has been solved by me. You may close it.
